{
  "region": "New York",
  "region_id": 24,
  "region_code": "NY",
  "country_id": "US",
  "street": "123 Oak Ave",
  "postcode": "10577",
  "city": "Purchase",
  "firstname": "Jane",
  "lastname": "Doe",
  "email": "jdoe@example.com",
  "telephone": "512-555-1111",
  "billing_region": "New York",
  "billing_region_id": 43,
  "billing_region_code": "NY",
  "billing_country_id": "US",
  "billing_street": "123 Oak Ave",
  "billing_postcode": "10577",
  "billing_city": "Purchase",
  "billing_firstname": "Jane",
  "billing_lastname": "Doe",
  "billing_email": "jdoe@example.com",
  "billing_telephone": "512-555-1111"
}